---
- hosts: webservers
  become: yes
  vars:
    db_root_password: "{{ vault_db_root_password }}"
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
    
    - name: Install Apache
      apt: 
        name: apache2
        state: present
    
    - name: Ensure Apache is running
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: Install MySQL Server
      apt: 
        name: 
          - mysql-server
          - python3-mysqldb
        state: present
      notify:
        - Start MySQL

    - name: Update MySQL root password for all root accounts
      mysql_user:
        name: root
        password: "{{ db_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Install PHP packages
      apt: 
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Copy over PHP info script
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/index.php

  handlers:
    - name: Start MySQL
      service: 
        name: mysql
        state: started
        enabled: yes
